require("core.configs.colorscheme")
require("core.configs.greeter")
require("core.configs.lualine")
require("core.configs.lsp-config")
require("core.configs.telescope")
require("core.configs.treesitter")
require("core.configs.none-ls")
require("core.configs.harpoon")
require("core.configs.completion")
require("core.configs.rust")
require("core.configs.oil")
require("core.configs.twilight")
require("core.configs.terminal")
require("core.configs.help-pages")
require("core.configs.neoscroll")
require("core.configs.yank")

-- require("core.configs.nvim-tree")
-- require("core.configs.autoclose")
